### ISSUE TITLE
section_64 is incorrectly defined

### ISSUE THREAD

**Issue by whyisthisfieldhere** [aidansteele/osx-abi-macho-file-format-reference#1]
This is a serious issue in apple's documentation they didn't bother to fix.
Maybe you will?

section_64 (unlike the 32 version) has an extra 'reserved3' field (to make the structure 64-bit aligned, I'd expect).

See definitions of section_64 (/etc.) in pretty much all code. E.g.  https://opensource.apple.com/source/xnu/xnu-792/EXTERNAL_HEADERS/mach-o/loader.h

**Comment by aidansteele** [comment]
Ooh nice catch! I'll try to fix that ASAP.

**Comment by Akaame** [comment]
Can we get this merged in? Was following this document for parser impl and had an issue because this was missing.

**Comment by aidansteele** [comment]
@Akaame Thanks for the reminder, I've merged @0xbf00's PR now
